targets:
  $default:
    sources:
      exclude:
        - "example/**"
    builders:
      json_serializable:
        options:
          include_if_null: true
          explicit_to_json: true
          field_rename: snake
