// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'admin_model.freezed.dart';
// optional: Since our AdminModel class is serializable, we must add this line.
// But if AdminModel was not serializable, we could skip it.
part 'admin_model.g.dart';

@freezed
class AdminModel with _$AdminModel {
  const factory AdminModel({
    required String id,
    required String name,
    required String profilePhoto,
    required String phone,
    required String createdAt,
    required String strikeCount,
    required String updatedAt,
    required String hashedPassword,
  }) = _AdminModel;

  factory AdminModel.fromJson(Map<String, Object?> json) =>
      _$AdminModelFromJson(json);
}
