// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:pizza_striker/logic/api/admin/models/admin_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'full_admin_model.freezed.dart';
// optional: Since our FullAdminModel class is serializable, we must add this line.
// But if FullAdminModel was not serializable, we could skip it.
part 'full_admin_model.g.dart';

@freezed
class FullAdminModel with _$FullAdminModel {
  const factory FullAdminModel({
    required String accessToken,
    required AdminModel admin,
  }) = _FullAdminModel;

  factory FullAdminModel.fromJson(Map<String, Object?> json) =>
      _$FullAdminModelFromJson(json);
}
