// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:pizza_striker/logic/api/user/models/full_user_model.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'leaderboard_response_model.freezed.dart';
// optional: Since our LeaderBoardResponseModel class is serializable, we must add this line.
// But if LeaderBoardResponseModel was not serializable, we could skip it.
part 'leaderboard_response_model.g.dart';

@freezed
class LeaderBoardResponseModel with _$LeaderBoardResponseModel {
  const factory LeaderBoardResponseModel({
    required List<FullUserModel> items,
    required int total,
    required int page,
    required int size,
    required int pages,
  }) = _LeaderBoardResponseModel;

  factory LeaderBoardResponseModel.fromJson(Map<String, Object?> json) =>
      _$LeaderBoardResponseModelFromJson(json);
}
