default_platform(:android)

platform :android do
  desc "Build and distribute Android app to Firebase App Distribution"
  lane :beta do

    # Clean Flutter build
    sh("flutter clean")

    # Build Flutter APK (Release)
    sh("flutter build apk --release")

    # Distribute APK via Firebase App Distribution
    firebase_app_distribution(
      app: "1:580856308707:android:727fc6db6b8988693176d6",
      groups: "internal-testers",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk"
    )
  end
end
